config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :kudos
  devise_for :employees


  root to: "kudos#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/kudo.rb
class Kudo < ApplicationRecord
  belongs_to :giver, class_name: 'Employee'
  belongs_to :receiver, class_name: 'Employee'

  validates :title, :content, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_employee!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kudos_controller.rb
class KudosController < ApplicationController
  before_action :set_kudo, only: [:show, :edit, :update, :destroy]

  # GET /kudos
  def index
    @kudos = Kudo.all
  end

  # GET /kudos/1
  def show
  end

  # GET /kudos/new
  def new
    @kudo = Kudo.new
  end

  # GET /kudos/1/edit
  def edit
  end

  # POST /kudos
  def create
    @kudo = Kudo.new(kudo_params)
    @kudo.giver = current_employee

    if @kudo.save
      redirect_to kudos_path, notice: 'Kudo was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /kudos/1
  def update
    if @kudo.update(kudo_params)
      redirect_to @kudo, notice: 'Kudo was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /kudos/1
  def destroy
    @kudo.destroy
    redirect_to kudos_url, notice: 'Kudo was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kudo
      @kudo = Kudo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kudo_params
      params.require(:kudo).permit(:title, :content, :giver, :receiver_id)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
Hello World

app/views/kudos/_form.html.erb
<%= form_with(model: kudo) do |form| %>
  <% if kudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kudo.errors.count, "error") %> prohibited this kudo from being saved:</h2>

      <ul>
        <% kudo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %> 
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>


  <div class="field">
    <%= form.label :receiver_id %>
    <%= form.collection_select :receiver_id, Employee.where.not(id: current_employee.id), :id, :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kudos/edit.html.erb
<h1>Editing Kudo</h1>

<%= render 'form', kudo: @kudo %>

<%= link_to 'Show', @kudo %> |
<%= link_to 'Back', kudos_path %>

app/views/kudos/index.html.erb
<h1>Kudos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Giver</th>
      <th>Receiver</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kudos.each do |kudo| %>
      <tr>
        <td><%= kudo.title %></td>
        <td><%= kudo.content %></td>
        <td><%= kudo.giver.email %></td>
        <td><%= kudo.receiver.email %></td>
        <td><%= link_to 'Show', kudo %></td>
        <td><%= link_to 'Edit', edit_kudo_path(kudo) %></td>
        <td><%= link_to 'Destroy', kudo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kudo', new_kudo_path %>

app/views/kudos/new.html.erb
<h1>New Kudo</h1>

<%= render 'form', kudo: @kudo %>

<%= link_to 'Back', kudos_path %>

app/views/kudos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @kudo.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @kudo.content %>
</p>

<p>
  <strong>Giver:</strong>
  <%= @kudo.giver_id %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @kudo.receiver_id %>
</p>

<%= link_to 'Edit', edit_kudo_path(@kudo) %> |
<%= link_to 'Back', kudos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Recognition Platform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <h1><%= link_to 'Company', root_url %></h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav>
      <h4>Navigate</h4>
      <ul>
        <% if !employee_signed_in? %>
          <li><%= link_to 'Sign in', new_employee_session_path %></li>
          <li><%= link_to 'Sign up', new_employee_registration_path %></li>
        <% else %>
          <li><%= link_to 'Sign out', destroy_employee_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </nav> 

    <%= yield %>
  </body>
</html>